
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.calculator': 'Estimation',
    'nav.contact': 'Contact',
    'nav.quote': 'Estimation',
    'nav.booking': 'Réservation',
    'nav.reserve': 'Réservation',
    
    // Hero Section
    'hero.title': 'Service Mobile de Pneus et Mécanique',
    'hero.subtitle': 'Nous venons vers vous ! Service professionnel à domicile',
    'hero.cta': 'Obtenir un devis',
    'hero.phone': 'Appelez maintenant',
    
    // Slider
    'slider.slide1.title': 'Changement de Pneus',
    'slider.slide1.desc': 'Service rapide et professionnel',
    'slider.slide2.title': 'Mécanique Mobile',
    'slider.slide2.desc': 'Diagnostics et réparations sur place',
    'slider.slide3.title': 'Service 7 jours sur 7',
    'slider.slide3.desc': 'Service rapide de 8h00 à 18h00',
    
    // Services
    'services.title': 'Nos Services',
    'services.subtitle': 'Services professionnels à votre porte',
    'services.tires': 'Services de Pneus',
    'services.mechanics': 'Mécanique Générale',
    'services.starting': 'À partir de',
    'services.duration': 'Durée estimée',
    'services.minutes': 'minutes',
    'services.book': 'Réserver',
    'services.book.now': 'Réserver maintenant',
    'services.loading': 'Chargement des services...',
    'services.error': 'Erreur lors du chargement des services',
    'services.retry': 'Réessayer',
    
    // Services détaillés
    'services.tire.seasonal': 'Changement de pneus saisonnier',
    'services.tire.seasonal.desc': 'Option 1: 4 pneus déjà sur jante (RIM) ou (MAG) 80$ sans supplément. Option 2: 4 pneus neufs ou usagés qui ne sont pas déjà sur des jantes (RIM) ou (MAG) supplément de 50$.',
    'services.tire.repair': 'Réparation de pneus',
    'services.tire.repair.desc': '1 réparation de pneus coûte 45$ et 20$ supplémentaire pour chaque pneus additionnels pour un maximum de 4 pneus.',
    'services.oil.change': 'Vidange d\'huile',
    'services.oil.change.desc': 'Huile Standard (5 litres sans extra) + filtre 15$, et l\'option huile synthétique (+50$) (5 litres maximum) sans extra + filtre 15$. Prix de base: 65$.',
    'services.brake.replacement': 'Remplacement de freins',
    'services.brake.replacement.desc': '2 roues 150$ + pièces, 4 roues 250$ + pièces.',
    'services.battery.replacement': 'Remplacement de batterie',
    'services.battery.replacement.desc': 'Installation d\'une nouvelle batterie automobile + pièces',
    'services.diagnostic': 'Diagnostic automobile (Lecture de code)',
    'services.diagnostic.desc': 'Diagnostic complet de votre véhicule avec lecture des codes d\'erreur',
    'services.maintenance.custom': 'Entretien à la carte',
    'services.maintenance.custom.desc': 'Le client doit choisir 1 de ces choix: 2 jambes de suspensions avant ou arrière ou moins, 6 injecteurs ou moins, 6 bougies ou moins, 1 couvercle de valve, 1 alternateur, 2 courroies ou moins, 1 étrier de freins, 1 pompe à eau, 1 valve EGR, 1 silencieux, 2 capteurs O2 ou moins, 1 pompe à carburant, 1 thermostat. *Pièces en sus.',
    
    // Service Booking
    'booking.title': 'Réservation de Service',
    'booking.subtitle': 'Réservez votre service automobile mobile',
    'booking.select.service': 'Sélectionnez votre service',
    'booking.select.date': 'Choisissez une date',
    'booking.select.time': 'Choisissez un créneau',
    'booking.customer.info': 'Informations client',
    'booking.parts.option': 'Options pièces',
    'booking.parts.search': 'Rechercher les pièces pour moi (+20$)',
    'booking.parts.have': 'J\'ai déjà mes pièces',
    'booking.parts.warranty.note': 'Note: Si vous avez vos propres pièces, seule la garantie main-d\'œuvre s\'applique.',
    'booking.payment': 'Paiement',
    'booking.summary': 'Résumé de la réservation',
    'booking.confirm': 'Confirmer la réservation',
    'booking.success': 'Réservation confirmée avec succès !',
    'booking.error': 'Erreur lors de la réservation',
    'booking.minimum.72h': 'Les réservations doivent être faites au minimum 72 heures à l\'avance',
    'booking.slot.unavailable': 'Ce créneau n\'est plus disponible',
    'booking.summary.service': 'Service sélectionné',
    'booking.summary.date': 'Date',
    'booking.summary.time': 'Heure',
    'booking.summary.customer': 'Client',
    'booking.summary.address': 'Adresse',
    'booking.summary.phone': 'Téléphone',
    'booking.summary.email': 'Courriel',
    'booking.summary.parts': 'Pièces',
    'booking.summary.travel.cost': 'Frais de déplacement',
    'booking.summary.service.cost': 'Coût du service',
    'booking.summary.parts.cost': 'Recherche de pièces',
    'booking.summary.subtotal': 'Sous-total',
    'booking.summary.taxes': 'Taxes (14,975%)',
    'booking.summary.total': 'Total',
    
    // Home Page - Section avantages
    'home.advantages.title': 'Pourquoi nous choisir?',
    'home.advantages.subtitle': 'Des avantages qui font la différence',
    'home.advantage.mobile.title': 'Mécanique Mobile',
    'home.advantage.mobile.desc': 'Dans un rayon de 100 KM',
    'home.advantage.fast.title': 'Intervention Rapide',
    'home.advantage.fast.desc': 'Service dans les 72 heures',
    'home.advantage.quality.title': 'Garantie qualité',
    'home.advantage.quality.desc': 'Travail garanti et assuré',
    'home.advantage.certified.title': 'Recherches de pièces',
    'home.advantage.certified.desc': 'On les recherches pour vous!',
    
    // Home Page - Section CTA
    'home.cta.title': 'Prêt à réserver votre service ?',
    'home.cta.subtitle': 'Obtenez une estimation gratuite en quelques clics ou réservez directement',
    'home.cta.view.all': 'Voir tous les services',
    'home.cta.book.now': 'Réserver maintenant',
    
    // Calculator - Estimation
    'calc.title': 'Estimation de Prix',
    'calc.subtitle': 'Obtenez une estimation instantanée pour vos services',
    'calc.select.services': 'Sélectionnez vos services',
    'calc.distance': 'Distance de déplacement (km)',
    'calc.customer.info': 'Informations client',
    'calc.name': 'Nom complet',
    'calc.email': 'Adresse email',
    'calc.phone': 'Téléphone',
    'calc.address': 'Adresse complète',
    'calc.date': 'Date préférée',
    'calc.notes': 'Notes additionnelles',
    'calc.summary': 'Résumé de l\'estimation',
    'calc.services.selected': 'Services sélectionnés',
    'calc.travel.cost': 'Frais de déplacement',
    'calc.subtotal': 'Sous-total',
    'calc.taxes': 'Taxes',
    'calc.taxes.gst': 'TPS (5%)',
    'calc.taxes.qst': 'TVQ (9,975%)',
    'calc.taxes.total': 'Total taxes (14,975%)',
    'calc.total': 'Total',
    'calc.submit': 'Demander cette estimation',
    'calc.success': 'Estimation envoyée avec succès !',
    'calc.error': 'Erreur lors de l\'envoi de l\'estimation',
    'calc.guarantee.opc': 'Garantie légale OPC incluse',
    'calc.guarantee.details': '3 mois/5000km - 6 mois/10000km selon service',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Service mobile professionnel • Réponse rapide • Satisfaction garantie',
    'contact.direct.title': 'Informations',
    'contact.phone.title': 'Téléphone',
    'contact.phone.available': 'Disponible 7 jours sur 7',
    'contact.email.title': 'Courriel',
    'contact.email.response': 'Réponse sous 2h',
    'contact.hours.title': 'Heures d\'ouverture',
    'contact.hours.daily': 'Lundi au dimanche : 8h00 à 18h00',
    'contact.hours.available': 'Service disponible tous les jours',
    'contact.chat.title': 'Clavardage en Direct',
    'contact.chat.desc': 'Besoin d\'une réponse immédiate ? Discutez avec nous via Facebook Messenger !',
    'contact.chat.button': 'Ouvrir Messenger',
    'contact.payment.title': 'Paiements Acceptés',
    'contact.payment.online': 'Paiement en ligne',
    'contact.payment.cash': 'Argent comptant',
    'contact.payment.debit': 'Débit',
    'contact.payment.credit': 'Crédit',
    'contact.guarantees.title': 'Nos Garanties',
    'contact.guarantees.professionals': 'Techniciens Qualifiés',
    'contact.guarantees.professionals.desc': 'Techniciens expérimentés et qualifiés',
    'contact.guarantees.opc': 'Garantie Légale',
    'contact.guarantees.opc.desc': 'Conformité légale assurée',
    'contact.guarantees.satisfaction': 'Satisfaction Client',
    'contact.guarantees.satisfaction.desc': 'Service de qualité garanti',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.name': 'Nom complet *',
    'contact.form.phone': 'Téléphone *',
    'contact.form.email': 'Adresse courriel *',
    'contact.form.subject': 'Sujet *',
    'contact.form.message': 'Message *',
    'contact.form.send': 'Envoyer le message',
    'contact.service.zone.title': 'Zone de Service',
    'contact.service.regions': 'Régions desservies',
    'contact.service.montreal': 'Montréal',
    'contact.service.laval': 'Laval',
    'contact.service.south.shore': 'Rive-Sud',
    'contact.service.north.shore': 'Rive-Nord',
    'contact.travel.fees.title': 'Frais de déplacement',
    'contact.travel.fees.rate': 'Tarif : 0,76$ par kilomètre',
    'contact.travel.fees.calculated': 'Calculé automatiquement selon votre adresse',
    'contact.travel.fees.maximum': 'Maximum : 76$ par déplacement',
    'contact.travel.fees.no.extra': 'Aucun frais supplémentaire au-delà',
    
    // Footer - TRADUCTIONS FRANÇAISES
    'footer.description': 'Service mobile professionnel de pneus et mécanique. Nous nous déplaçons chez vous pour tous vos besoins automobiles.',
    'footer.services.title': 'Nos Services',
    'footer.contact.info': 'Informations',
    'footer.follow': 'Suivez-nous',
    'footer.copyright': '© 2025 JJ Mécanique Mobile. Tous droits réservés.',
    'footer.newsletter.title': 'Infolettre',
    'footer.newsletter.description': 'Recevez nos dernières nouvelles et offres spéciales',
    'footer.newsletter.email': 'Votre adresse email',
    'footer.newsletter.subscribe': 'S\'abonner',
    'footer.newsletter.success': 'Inscription réussie à l\'infolettre !',
    'footer.services.seasonal': 'Changement de pneus saisonnier',
    'footer.services.repair': 'Réparation de crevaison',
    'footer.services.oil': 'Changement d\'huile mobile',
    'footer.services.battery': 'Remplacement de batterie',
    'footer.services.brakes': 'Remplacement de freins',
    'footer.services.calculator': 'Estimation de prix',
    'footer.service.area': 'Montréal et environs',
    'footer.service.radius': 'Rayon de service: 100 km',
    'footer.travel.fees': 'Frais déplacement: 0,61$ /km',
    'footer.privacy.policy': 'Politique de confidentialité',
    'footer.terms.conditions': 'Conditions générales',
    'footer.login': 'Espace client',
    
    // Politique de confidentialité
    'privacy.title': 'Politique de Confidentialité',
    'privacy.last.updated': 'Dernière mise à jour',
    'privacy.intro': 'Chez JJ Mécanique, nous nous engageons à protéger votre vie privée et vos données personnelles. Cette politique de confidentialité explique comment nous collectons, utilisons, stockons et protégeons vos informations lorsque vous utilisez nos services de mécanique mobile.',
    'privacy.collection.title': 'Collecte d\'informations',
    'privacy.collection.content': 'Nous collectons les informations que vous nous fournissez directement lors de l\'utilisation de nos services, notamment :\n• Informations de contact (nom, email, téléphone, adresse)\n• Informations sur vos véhicules et besoins de service\n• Historique des services et préférences\n• Données de navigation sur notre site web',
    'privacy.usage.title': 'Utilisation des données',
    'privacy.usage.content': 'Vos informations personnelles sont utilisées pour :\n• Fournir nos services de mécanique mobile\n• Planifier et confirmer vos rendez-vous\n• Traiter vos paiements de manière sécurisée\n• Améliorer nos services et votre expérience\n• Vous envoyer des communications importantes sur vos services',
    'privacy.protection.title': 'Protection des données',
    'privacy.protection.content': 'Nous mettons en place des mesures de sécurité appropriées pour protéger vos informations :\n• Chiffrement SSL pour toutes les transmissions de données\n• Accès restreint aux données personnelles\n• Stockage sécurisé avec sauvegarde régulière\n• Formation du personnel sur la protection des données',
    'privacy.rights.title': 'Vos droits',
    'privacy.rights.content': 'Vous avez le droit de :\n• Accéder à vos données personnelles\n• Corriger ou mettre à jour vos informations\n• Demander la suppression de vos données\n• Vous opposer au traitement de vos données\n• Recevoir une copie de vos données dans un format portable',
    'privacy.sharing.title': 'Partage d\'informations',
    'privacy.sharing.content': 'Nous ne vendons, ne louons ni ne partageons vos informations personnelles avec des tiers, sauf dans les cas suivants :\n• Avec votre consentement explicite\n• Pour fournir les services que vous avez demandés\n• Pour respecter les obligations légales\n• Pour protéger nos droits et notre sécurité',
    'privacy.contact.title': 'Questions sur cette politique ?',
    'privacy.contact.content': 'Si vous avez des questions concernant cette politique de confidentialité, n\'hésitez pas à nous contacter.',
    
    // Termes et conditions
    'terms.title': 'Conditions Générales de Vente',
    'terms.subtitle': 'JJ Mécanique Mobile - Service professionnel à domicile',
    'terms.last.updated': 'Dernière mise à jour',
    'terms.general.title': 'Informations Générales',
    'terms.general.content': 'JJ Mécanique est un service mobile de mécanique automobile et de changement de pneus opérant dans la région du Grand Montréal et ses environs.',
    'terms.contact.info': 'Coordonnées de contact :',
    'terms.services.title': 'Services Offerts',
    'terms.services.content': 'Nos services incluent mais ne se limitent pas à :',
    'terms.services.list': '• Changement et installation de pneus\n• Réparation et remplacement de freins\n• Changement d\'huile et entretien général\n• Diagnostic et réparations mécaniques\n• Service de démarrage et assistance routière',
    'terms.hours.title': 'Heures d\'ouverture :',
    'terms.hours.content': 'Lundi au dimanche : 8h00 à 18h00\nService d\'urgence disponible sur demande',
    'terms.pricing.title': 'Tarification et Frais de Déplacement',
    'terms.travel.fees': 'Frais de déplacement :',
    'terms.travel.rate': 'Tarif : 0,61$ par kilomètre parcouru',
    'terms.travel.maximum': 'Maximum : 55$ par déplacement',
    'terms.travel.calculation': 'Calcul : Distance calculée automatiquement selon l\'adresse du client',
    'terms.travel.zone': 'Zone de service : Rayon de 100 km maximum',
    'terms.taxes.title': 'Taxes :',
    'terms.taxes.content': 'Tous les prix sont assujettis aux taxes en vigueur au Québec :',
    'terms.taxes.gst': 'TPS (Taxe sur les produits et services) : 5%',
    'terms.taxes.qst': 'TVQ (Taxe de vente du Québec) : 9,975%',
    'terms.taxes.total': 'Total des taxes : 14,975%',
    'terms.cancellation.title': 'Politique d\'Annulation et Remboursement',
    'terms.cancellation.24h.title': 'Annulation 24 heures ou plus à l\'avance',
    'terms.cancellation.24h.content': 'Remboursement intégral à 100% de tous les montants payés, incluant les services et les frais de déplacement.',
    'terms.cancellation.less24h.title': 'Annulation moins de 24 heures à l\'avance',
    'terms.cancellation.less24h.services': 'Services : Remboursement à 100%',
    'terms.cancellation.less24h.travel': 'Frais de déplacement : Non remboursables (0,61$/km)',
    'terms.cancellation.absent.title': 'Absence du client au rendez-vous',
    'terms.cancellation.absent.content': 'Si le client n\'est pas présent à l\'adresse convenue lors du rendez-vous, les frais de déplacement engagés ne pourront pas être remboursés.',
    'terms.refund.title': 'Modalités de remboursement :',
    'terms.refund.timeline': 'Les remboursements sont traités dans un délai de 5 à 10 jours ouvrables',
    'terms.refund.method': 'Le remboursement s\'effectue par le même moyen de paiement utilisé',
    'terms.refund.confirmation': 'Une confirmation de remboursement sera envoyée par courriel',
    'terms.payment.title': 'Modes de Paiement',
    'terms.payment.accepted': 'Nous acceptons les modes de paiement suivants :',
    'terms.payment.cash': 'Argent comptant',
    'terms.payment.debit': 'Cartes de débit (Interac)',
    'terms.payment.credit': 'Cartes de crédit (Visa, MasterCard)',
    'terms.payment.transfer': 'Virement Interac',
    'terms.invoice.title': 'Facturation :',
    'terms.invoice.content': 'Une facture détaillée sera fournie après chaque service, incluant la description des travaux effectués et les garanties applicables.',
    'terms.warranty.title': 'Garanties et Responsabilités',
    'terms.warranty.opc.title': 'Garantie légale OPC :',
    'terms.warranty.opc.content': 'Conformément à la réglementation de l\'Office de la Protection du Consommateur (OPC), nos services sont couverts par les garanties légales suivantes :',
    'terms.warranty.parts': 'Pièces et main-d\'œuvre : 3 mois ou 5 000 km (selon la première échéance)',
    'terms.warranty.specialized': 'Services spécialisés : 6 mois ou 10 000 km (selon la première échéance)',
    'terms.warranty.new.parts': 'Pièces neuves : Garantie du manufacturier applicable',
    'terms.warranty.limitations.title': 'Limitations :',
    'terms.warranty.limitations.wear': 'La garantie ne couvre pas l\'usure normale des pièces',
    'terms.warranty.limitations.damage': 'Les dommages causés par une mauvaise utilisation ou un accident ne sont pas couverts',
    'terms.warranty.limitations.receipt': 'Le client doit conserver sa facture pour faire valoir la garantie',
    'terms.general.provisions.title': 'Dispositions Générales',
    'terms.modifications.title': 'Modification des conditions :',
    'terms.modifications.content': 'JJ Mécanique se réserve le droit de modifier ces conditions générales de vente à tout moment. Les nouvelles conditions seront applicables aux services commandés après leur mise en ligne.',
    'terms.applicable.law.title': 'Droit applicable :',
    'terms.applicable.law.content': 'Ces conditions générales de vente sont régies par les lois du Québec et du Canada. Tout litige sera soumis aux tribunaux compétents du Québec.',
    'terms.data.protection.title': 'Protection des données :',
    'terms.data.protection.content': 'Vos informations personnelles sont protégées conformément à notre politique de confidentialité.',
    'terms.questions.title': 'Questions sur nos conditions générales ?',
    'terms.questions.content': 'N\'hésitez pas à nous contacter pour toute clarification :',

    // NOUVELLES SECTIONS 8-12 - FRANÇAIS
    'terms.parts.title': 'Pièces Mécaniques',
    'terms.parts.payment': 'Toutes les pièces sont en sus et le paiement de celles-ci doit être réglé au maximum 24 heures avant la journée du rendez-vous.',
    'terms.parts.search.fees': 'Bien que nous nous efforçons de trouver le meilleur prix possible pour vos pièces, les frais payés pour la recherche de pièces ne sont pas remboursables dans le cas échéant où le client n\'accepte pas le devis.',
    'terms.parts.options': 'Nous vous fournirons 2 prix pour vos pièces : pièces OEM et pièces génériques en respectant bien sûr, les normes de qualité et de sécurité de votre véhicule.',

    'terms.exclusions.title': 'Exclusions',
    'terms.exclusions.safety.title': 'Sécurité du technicien',
    'terms.exclusions.safety.content': 'JJ Mécanique se réserve le droit de refuser et d\'annuler le service si l\'espace de travail n\'est pas sécuritaire, dangereux ou si la sécurité d\'un ou des techniciens est menacée.',
    'terms.exclusions.vehicles.title': 'Véhicules exclus',
    'terms.exclusions.vehicles.trucks': 'Les camions de plus de 6 tonnes métriques, les pick-up, motos, bateaux, trottinettes, vélos, mobylettes, quadriporteurs, scooters et avions sont exclus de nos services.',
    'terms.exclusions.vehicles.german': 'Les voitures allemandes sont exclues de nos services jusqu\'à modification de nos termes.',
    'terms.exclusions.vehicles.non.canadian': 'Les voitures qui ne sont pas vendues au Canada sont exclues de nos services.',
    'terms.exclusions.vehicles.luxury': 'Les voitures luxueuses dont la valeur dépasse 100 000 dollars sont exclues de nos services.',
    'terms.exclusions.vehicles.emergency': 'Les véhicules d\'urgence et scolaires sont exclus de nos services, conformément à la loi du ministère des Transports du Québec.',
    'terms.exclusions.location.title': 'Restrictions de lieu',
    'terms.exclusions.location.street': 'Nous n\'effectuerons aucun service dans la rue, mis à part le changement de pneus et de batterie. Le client doit disposer d\'une place de stationnement privée et sécuritaire pour que nos techniciens puissent effectuer le travail.',
    'terms.exclusions.location.private': 'Si vous disposez d\'une autorisation pour effectuer des réparations mécaniques dans un endroit privé dont vous n\'êtes pas propriétaire (exemple : à votre travail), avisez le technicien à l\'avance lors de son arrivée s\'il vous plaît.',
    'terms.exclusions.location.authorization': 'Pour le moment, nous n\'effectuons aucun travail après sinistre pour l\'assurance. Les paiements via les assureurs canadiens ou étrangers ne sont pas acceptés. Seuls les modes de paiement mentionnés dans la page de contact du site sont acceptés.',
    'terms.exclusions.weather.title': 'Conditions météorologiques',
    'terms.exclusions.weather.snow': 'Le ou les services seront automatiquement annulés ou reportés si l\'endroit privé attribué pour le travail n\'est pas déneigé ou déglacé ou si cela représente un risque pour la sécurité.',
    'terms.exclusions.weather.temperature': 'Le ou les services seront automatiquement annulés si la météo incluant les facteurs éoliens et de refroidissement, à l\'exception du changement de pneus et de batterie, dépassent les -18 degrés.',
    'terms.exclusions.insurance.title': 'Assurance',
    'terms.exclusions.insurance.content': 'Pour le moment, nous n\'effectuons aucun travail après sinistre pour l\'assurance. Les paiements via les assureurs canadiens ou étrangers ne sont pas acceptés.',

    'terms.tips.title': 'Pourboires et Relations avec la Clientèle',
    'terms.tips.policy': 'Les pourboires ne sont pas obligatoires, mais ils sont acceptés à votre discrétion.',
    'terms.tips.access.title': 'Accès aux lieux',
    'terms.tips.access.content': 'Pour limiter les conflits, aucun technicien n\'a l\'autorisation d\'entrer dans votre demeure ou dans un espace qui n\'est pas attribué à la réparation du véhicule. Exemple : aller chercher une pièce ou des pneus dans votre sous-sol.',
    'terms.tips.preparation.title': 'Préparation du client',
    'terms.tips.preparation.content': 'Le jour de votre rendez-vous, assurez-vous que dans le cas échéant, toutes les pièces sont à proximité pour optimiser le temps du technicien.',
    'terms.tips.electrical': 'Bien que nos techniciens soient équipés d\'outils sans fil, il se peut qu\'à l\'occasion ils vous demandent de brancher une rallonge électrique.',

    'terms.road.tests.title': 'Essais Routiers',
    'terms.road.tests.procedure': 'Le technicien effectuera un ou des essais routiers avant ou après les travaux sur votre véhicule dans le cas échéant.',
    'terms.road.tests.license': 'Tous nos techniciens disposent d\'un permis de conduire valide au moment du service.',
    'terms.road.tests.insurance': 'Nous sommes couverts en cas d\'accident pour les véhicules qui ne nous appartiennent pas.',

    'terms.environmental.title': 'Frais Environnementaux et Disposition des Pièces Usagées',
    'terms.environmental.fees.included': 'Tous les frais environnementaux pour la récupération des pièces défectueuses, des huiles usées et des filtres sont inclus dans le prix.',
    'terms.environmental.disposal.title': 'Disposition des pièces',
    'terms.environmental.disposal.parts': 'À l\'exception des batteries fournies par nos services, toutes les pièces usagées, emballages et matières plastiques seront jetés de façon à respecter l\'environnement.',
    'terms.environmental.disposal.keep': 'Il est de votre droit de conserver vos pièces usagées, sans frais supplémentaires, vous n\'avez qu\'à le mentionner à votre technicien.',
    'terms.environmental.disposal.no.used': 'JJ Mécanique n\'installera en aucun cas, aucune pièce usagée sur votre véhicule.',
    'terms.environmental.protection': 'Nos techniciens disposent de l\'équipement adéquat pour ne pas salir votre propriété. Toutes les huiles usagées seront disposées de façon écoresponsable sans frais supplémentaires.',
    
    // Espace client
    'client.portal.title': 'Espace Client',
    'client.portal.subtitle': 'Gérez vos factures et historique de services',
    'client.portal.welcome': 'Bienvenue dans votre espace client',
    'client.portal.description': 'Consultez vos factures, téléchargez vos reçus et suivez l\'historique de vos services.',
    'client.portal.search.placeholder': 'Rechercher par numéro de facture, email ou téléphone...',
    'client.portal.search.button': 'Rechercher',
    'client.portal.invoice.number': 'Facture #',
    'client.portal.date': 'Date',
    'client.portal.service': 'Service',
    'client.portal.amount': 'Montant',
    'client.portal.status': 'Statut',
    'client.portal.actions': 'Actions',
    'client.portal.download': 'Télécharger',
    'client.portal.view': 'Voir',
    'client.portal.paid': 'Payé',
    'client.portal.pending': 'En attente',
    'client.portal.no.invoices': 'Aucune facture trouvée',
    'client.portal.search.tip': 'Utilisez votre email ou numéro de téléphone pour retrouver vos factures',
    'client.portal.loading': 'Chargement...',
    'client.portal.error': 'Erreur lors de la recherche',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.success': 'Succès !',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.reserve': 'Réserver',
    'common.book': 'Réserver'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.calculator': 'Estimate',
    'nav.contact': 'Contact',
    'nav.quote': 'Free Quote',
    'nav.booking': 'Booking',
    'nav.reserve': 'Reservation',
    
    // Hero Section
    'hero.title': 'Mobile Tire and Mechanical Service',
    'hero.subtitle': 'We come to you! Professional service at your location',
    'hero.cta': 'Get a quote',
    'hero.phone': 'Call now',
    
    // Slider
    'slider.slide1.title': 'Tire Change Service',
    'slider.slide1.desc': 'Fast and professional service',
    'slider.slide2.title': 'Expert Mobile Mechanics',
    'slider.slide2.desc': 'Diagnostics and repairs on-site',
    'slider.slide3.title': 'Available 7 Days a Week',
    'slider.slide3.desc': 'Quality service from 8:00 AM to 6:00 PM',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Professional services at your doorstep',
    'services.tires': 'Tire Services',
    'services.mechanics': 'General Mechanics',
    'services.starting': 'Starting from',
    'services.duration': 'Estimated duration',
    'services.minutes': 'minutes',
    'services.book': 'Book',
    'services.book.now': 'Book now',
    'services.loading': 'Loading services...',
    'services.error': 'Error loading services',
    'services.retry': 'Retry',
    
    // Services détaillés EN ANGLAIS
    'services.tire.seasonal': 'Seasonal tire change',
    'services.tire.seasonal.desc': 'Option 1: 4 tires already on rim (RIM) or (MAG) $80 no extra charge. Option 2: 4 new or used tires not already on rims (RIM) or (MAG) $50 surcharge.',
    'services.tire.repair': 'Tire repair',
    'services.tire.repair.desc': '1 tire repair costs $45 and $20 additional for each additional tire for a maximum of 4 tires.',
    'services.oil.change': 'Oil change',
    'services.oil.change.desc': 'Standard Oil (5 liters without extra) + filter $15, and synthetic oil option (+$50) (5 liters maximum) without extra + filter $15. Base price: $65.',
    'services.brake.replacement': 'Brake replacement',
    'services.brake.replacement.desc': '2 wheels $150 + parts, 4 wheels $250 + parts.',
    'services.battery.replacement': 'Battery replacement',
    'services.battery.replacement.desc': 'Installation of a new car battery + parts',
    'services.diagnostic': 'Automotive diagnostic (Code reading)',
    'services.diagnostic.desc': 'Complete vehicle diagnostic with error code reading',
    'services.maintenance.custom': 'Custom maintenance',
    'services.maintenance.custom.desc': 'Customer must choose 1 of these options: 2 front or rear suspension struts or less, 6 injectors or less, 6 spark plugs or less, 1 valve cover, 1 alternator, 2 belts or less, 1 brake caliper, 1 water pump, 1 EGR valve, 1 muffler, 2 O2 sensors or less, 1 fuel pump, 1 thermostat. *Parts extra.',
    
    // Service Booking
    'booking.title': 'Service Booking',
    'booking.subtitle': 'Book your mobile automotive service',
    'booking.select.service': 'Select your service',
    'booking.select.date': 'Choose a date',
    'booking.select.time': 'Choose a time slot',
    'booking.customer.info': 'Customer information',
    'booking.parts.option': 'Parts options',
    'booking.parts.search': 'Find parts for me (+$20)',
    'booking.parts.have': 'I already have my parts',
    'booking.parts.warranty.note': 'Note: If you have your own parts, only labor warranty applies.',
    'booking.payment': 'Payment',
    'booking.summary': 'Booking summary',
    'booking.confirm': 'Confirm booking',
    'booking.success': 'Booking confirmed successfully!',
    'booking.error': 'Error during booking',
    'booking.minimum.72h': 'Bookings must be made at least 72 hours in advance',
    'booking.slot.unavailable': 'This time slot is no longer available',
    'booking.summary.service': 'Selected service',
    'booking.summary.date': 'Date',
    'booking.summary.time': 'Time',
    'booking.summary.customer': 'Customer',
    'booking.summary.address': 'Address',
    'booking.summary.phone': 'Phone',
    'booking.summary.email': 'Email',
    'booking.summary.parts': 'Parts',
    'booking.summary.travel.cost': 'Travel cost',
    'booking.summary.service.cost': 'Service cost',
    'booking.summary.parts.cost': 'Parts search',
    'booking.summary.subtotal': 'Subtotal',
    'booking.summary.taxes': 'Taxes (14.975%)',
    'booking.summary.total': 'Total',
    
    // Home Page - Section avantages EN ANGLAIS
    'home.advantages.title': 'Why Choose Us?',
    'home.advantages.subtitle': 'Advantages that make the difference',
    'home.advantage.mobile.title': 'Mobile Mechanic',
    'home.advantage.mobile.desc': '100 KM radius mobile service',
    'home.advantage.fast.title': 'Fast Intervention',
    'home.advantage.fast.desc': 'Service within 72 hours',
    'home.advantage.quality.title': 'Quality guarantee',
    'home.advantage.quality.desc': 'Guaranteed and insured work',
    'home.advantage.certified.title': 'Parts searches',
    'home.advantage.certified.desc': 'Were looking for them for you!',
    
    // Home Page - Section CTA
    'home.cta.title': 'Ready to book your service?',
    'home.cta.subtitle': 'Get a free quote in just a few clicks or book directly',
    'home.cta.view.all': 'View all services',
    'home.cta.book.now': 'Book now',
    
    // Calculator - Estimate EN ANGLAIS
    'calc.title': 'Price Estimate',
    'calc.subtitle': 'Get an instant estimate for your services',
    'calc.select.services': 'Select your services',
    'calc.distance': 'Travel distance (km)',
    'calc.customer.info': 'Customer information',
    'calc.name': 'Full name',
    'calc.email': 'Email address',
    'calc.phone': 'Phone',
    'calc.address': 'Complete address',
    'calc.date': 'Preferred date',
    'calc.notes': 'Additional notes',
    'calc.summary': 'Estimate summary',
    'calc.services.selected': 'Selected services',
    'calc.travel.cost': 'Travel cost',
    'calc.subtotal': 'Subtotal',
    'calc.taxes': 'Taxes',
    'calc.taxes.gst': 'GST (5%)',
    'calc.taxes.qst': 'QST (9.975%)',
    'calc.taxes.total': 'Total taxes (14.975%)',
    'calc.total': 'Total',
    'calc.submit': 'Request this estimate',
    'calc.success': 'Estimate sent successfully!',
    'calc.error': 'Error sending estimate',
    'calc.guarantee.opc': 'OPC legal warranty included',
    'calc.guarantee.details': '3 months/5000km - 6 months/10000km depending on service',
    
    // Contact EN ANGLAIS
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Professional mobile service • Fast response • Guaranteed satisfaction',
    'contact.direct.title': 'Information',
    'contact.phone.title': 'Phone',
    'contact.phone.available': 'Available 7 days a week',
    'contact.email.title': 'Email',
    'contact.email.response': 'Response within 2h',
    'contact.hours.title': 'Business Hours',
    'contact.hours.daily': 'Monday to Sunday: 8:00 AM to 6:00 PM',
    'contact.hours.available': 'Service available every day',
    'contact.chat.title': 'Live Chat',
    'contact.chat.desc': 'Need an immediate response? Chat with us via Facebook Messenger!',
    'contact.chat.button': 'Open Messenger',
    'contact.payment.title': 'Accepted Payments',
    'contact.payment.online': 'Online payment',
    'contact.payment.cash': 'Cash',
    'contact.payment.debit': 'Debit',
    'contact.payment.credit': 'Credit',
    'contact.guarantees.title': 'Our Guarantees',
    'contact.guarantees.professionals': 'Certified Professionals',
    'contact.guarantees.professionals.desc': 'Experienced and qualified technicians',
    'contact.guarantees.opc': 'Warranty',
    'contact.guarantees.opc.desc': 'Legal compliance ensured',
    'contact.guarantees.satisfaction': 'Customer Satisfaction',
    'contact.guarantees.satisfaction.desc': 'Quality service guaranteed',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Full name *',
    'contact.form.phone': 'Phone *',
    'contact.form.email': 'Email address *',
    'contact.form.subject': 'Subject *',
    'contact.form.message': 'Message *',
    'contact.form.send': 'Send message',
    'contact.service.zone.title': 'Service Area',
    'contact.service.regions': 'Areas served',
    'contact.service.montreal': 'Montreal',
    'contact.service.laval': 'Laval',
    'contact.service.south.shore': 'South Shore',
    'contact.service.north.shore': 'North Shore',
    'contact.travel.fees.title': 'Travel fees',
    'contact.travel.fees.rate': 'Rate: $0.76 per kilometer',
    'contact.travel.fees.calculated': 'Automatically calculated based on your address',
    'contact.travel.fees.maximum': 'Maximum: $76 per trip',
    'contact.travel.fees.no.extra': 'No additional fees beyond',
    
    // Footer - TRADUCTIONS ANGLAISES
    'footer.description': 'Professional mobile tire and mechanical service. We come to you for all your automotive needs.',
    'footer.services.title': 'Our Services',
    'footer.contact.info': 'Information',
    'footer.follow': 'Follow us',
    'footer.copyright': '© 2024 JJ Mobile Mechanics. All rights reserved.',
    'footer.newsletter.title': 'Newsletter',
    'footer.newsletter.description': 'Receive our latest news and special offers',
    'footer.newsletter.email': 'Your email address',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.newsletter.success': 'Successfully subscribed to newsletter!',
    'footer.services.seasonal': 'Seasonal tire change',
    'footer.services.repair': 'Tire puncture repair',
    'footer.services.oil': 'Mobile oil change',
    'footer.services.battery': 'Battery replacement',
    'footer.services.brakes': 'Brake replacement',
    'footer.services.calculator': 'Price calculator',
    'footer.service.area': 'Montreal and surroundings',
    'footer.service.radius': 'Service radius: 100 km',
    'footer.travel.fees': 'Travel fees: $0.61 /km',
    'footer.privacy.policy': 'Privacy Policy',
    'footer.terms.conditions': 'Terms and Conditions',
    'footer.login': 'Client Portal',
    
    // Privacy Policy EN ANGLAIS
    'privacy.title': 'Privacy Policy',
    'privacy.last.updated': 'Last updated',
    'privacy.intro': 'At JJ Mechanics, we are committed to protecting your privacy and personal data. This privacy policy explains how we collect, use, store and protect your information when you use our mobile mechanics services.',
    'privacy.collection.title': 'Information Collection',
    'privacy.collection.content': 'We collect information that you provide directly to us when using our services, including:\n• Contact information (name, email, phone, address)\n• Information about your vehicles and service needs\n• Service history and preferences\n• Website browsing data',
    'privacy.usage.title': 'Data Usage',
    'privacy.usage.content': 'Your personal information is used to:\n• Provide our mobile mechanics services\n• Schedule and confirm your appointments\n• Process your payments securely\n• Improve our services and your experience\n• Send you important communications about your services',
    'privacy.protection.title': 'Data Protection',
    'privacy.protection.content': 'We implement appropriate security measures to protect your information:\n• SSL encryption for all data transmissions\n• Restricted access to personal data\n• Secure storage with regular backups\n• Staff training on data protection',
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.content': 'You have the right to:\n• Access your personal data\n• Correct or update your information\n• Request deletion of your data\n• Object to the processing of your data\n• Receive a copy of your data in a portable format',
    'privacy.sharing.title': 'Information Sharing',
    'privacy.sharing.content': 'We do not sell, rent or share your personal information with third parties, except in the following cases:\n• With your explicit consent\n• To provide the services you have requested\n• To comply with legal obligations\n• To protect our rights and security',
    'privacy.contact.title': 'Questions about this policy?',
    'privacy.contact.content': 'If you have any questions about this privacy policy, please do not hesitate to contact us.',
    
    // Terms and Conditions EN ANGLAIS
    'terms.title': 'Terms and Conditions of Sale',
    'terms.subtitle': 'JJ Mobile Mechanics - Professional home service',
    'terms.last.updated': 'Last updated',
    'terms.general.title': 'General Information',
    'terms.general.content': 'JJ Mechanics is a mobile automotive mechanics and tire change service operating in the Greater Montreal area and surroundings.',
    'terms.contact.info': 'Contact information:',
    'terms.services.title': 'Services Offered',
    'terms.services.content': 'Our services include but are not limited to:',
    'terms.services.list': '• Tire change and installation\n• Brake repair and replacement\n• Oil change and general maintenance\n• Automotive diagnostics and repairs\n• Jump start service and roadside assistance',
    'terms.hours.title': 'Business hours:',
    'terms.hours.content': 'Monday to Sunday: 8:00 AM to 6:00 PM\nEmergency service available upon request',
    'terms.pricing.title': 'Pricing and Travel Fees',
    'terms.travel.fees': 'Travel fees:',
    'terms.travel.rate': 'Rate: $0.61 per kilometer traveled',
    'terms.travel.maximum': 'Maximum: $55 per trip',
    'terms.travel.calculation': 'Calculation: Distance automatically calculated based on customer address',
    'terms.travel.zone': 'Service area: Maximum 100 km radius',
    'terms.taxes.title': 'Taxes:',
    'terms.taxes.content': 'All prices are subject to taxes in effect in Quebec:',
    'terms.taxes.gst': 'GST (Goods and Services Tax): 5%',
    'terms.taxes.qst': 'QST (Quebec Sales Tax): 9.975%',
    'terms.taxes.total': 'Total taxes: 14.975%',
    'terms.cancellation.title': 'Cancellation and Refund Policy',
    'terms.cancellation.24h.title': 'Cancellation 24 hours or more in advance',
    'terms.cancellation.24h.content': '100% full refund of all amounts paid, including services and travel fees.',
    'terms.cancellation.less24h.title': 'Cancellation less than 24 hours in advance',
    'terms.cancellation.less24h.services': 'Services: 100% refund',
    'terms.cancellation.less24h.travel': 'Travel fees: Non-refundable ($0.61/km)',
    'terms.cancellation.absent.title': 'Customer absence at appointment',
    'terms.cancellation.absent.content': 'If the customer is not present at the agreed address during the appointment, the incurred travel fees cannot be refunded.',
    'terms.refund.title': 'Refund terms:',
    'terms.refund.timeline': 'Refunds are processed within 5 to 10 business days',
    'terms.refund.method': 'Refund is made using the same payment method used',
    'terms.refund.confirmation': 'A refund confirmation will be sent by email',
    'terms.payment.title': 'Payment Methods',
    'terms.payment.accepted': 'We accept the following payment methods:',
    'terms.payment.cash': 'Cash',
    'terms.payment.debit': 'Debit cards (Interac)',
    'terms.payment.credit': 'Credit cards (Visa, MasterCard)',
    'terms.payment.transfer': 'Interac transfer',
    'terms.invoice.title': 'Billing:',
    'terms.invoice.content': 'A detailed invoice will be provided after each service, including description of work performed and applicable warranties.',
    'terms.warranty.title': 'Warranties and Responsibilities',
    'terms.warranty.opc.title': 'legal warranty:',
    'terms.warranty.opc.content': 'In accordance with the Office de la Protection du Consommateur (OPC) regulations, our services are covered by the following legal warranties:',
    'terms.warranty.parts': 'Parts and labor: 3 months or 5,000 km (whichever comes first)',
    'terms.warranty.specialized': 'Specialized services: 6 months or 10,000 km (whichever comes first)',
    'terms.warranty.new.parts': 'New parts: Manufacturer warranty applies',
    'terms.warranty.limitations.title': 'Limitations:',
    'terms.warranty.limitations.wear': 'Warranty does not cover normal wear of parts',
    'terms.warranty.limitations.damage': 'Damage caused by misuse or accident is not covered',
    'terms.warranty.limitations.receipt': 'Customer must keep their invoice to claim warranty',
    'terms.general.provisions.title': 'General Provisions',
    'terms.modifications.title': 'Modification of conditions:',
    'terms.modifications.content': 'JJ Mechanics reserves the right to modify these terms and conditions of sale at any time. New conditions will apply to services ordered after they are posted online.',
    'terms.applicable.law.title': 'Applicable law:',
    'terms.applicable.law.content': 'These terms and conditions of sale are governed by the laws of Quebec and Canada. Any dispute will be submitted to the competent courts of Quebec.',
    'terms.data.protection.title': 'Data protection:',
    'terms.data.protection.content': 'Your personal information is protected in accordance with our privacy policy.',
    'terms.questions.title': 'Questions about our terms and conditions?',
    'terms.questions.content': 'Please do not hesitate to contact us for any clarification:',

    // NOUVELLES SECTIONS 8-12 - ENGLISH
    'terms.parts.title': 'Mechanical Parts',
    'terms.parts.payment': 'All parts are extra and payment for these must be settled no later than 24 hours before the appointment day.',
    'terms.parts.search.fees': 'Although we strive to find the best possible price for your parts, fees paid for parts search are non-refundable in the event that the customer does not accept the quote.',
    'terms.parts.options': 'We will provide you with 2 prices for your parts: OEM parts and generic parts while respecting, of course, the quality and safety standards of your vehicle.',

    'terms.exclusions.title': 'Exclusions',
    'terms.exclusions.safety.title': 'Technician safety',
    'terms.exclusions.safety.content': 'JJ Mechanics reserves the right to refuse and cancel service if the workspace is not safe, dangerous, or if the safety of one or more technicians is threatened.',
    'terms.exclusions.vehicles.title': 'Excluded vehicles',
    'terms.exclusions.vehicles.trucks': 'Trucks over 6 metric tons, pick-ups, motorcycles, boats, scooters, bicycles, mopeds, mobility scooters, scooters and aircraft are excluded from our services.',
    'terms.exclusions.vehicles.german': 'German cars are excluded from our services until modification of our terms.',
    'terms.exclusions.vehicles.non.canadian': 'Cars that are not sold in Canada are excluded from our services.',
    'terms.exclusions.vehicles.luxury': 'Luxury cars with a value exceeding $100,000 are excluded from our services.',
    'terms.exclusions.vehicles.emergency': 'Emergency and school vehicles are excluded from our services, in accordance with Quebec Ministry of Transportation law.',
    'terms.exclusions.location.title': 'Location restrictions',
    'terms.exclusions.location.street': 'We will not perform any service on the street, except for tire and battery changes. The customer must have a private and secure parking space for our technicians to perform the work.',
    'terms.exclusions.location.private': 'If you have authorization to perform mechanical repairs in a private location that you do not own (example: at your workplace), please notify the technician in advance upon arrival.',
    'terms.exclusions.location.authorization': 'At the moment, we do not perform any post-claim work for insurance. Payments via Canadian or foreign insurers are not accepted. Only the payment methods mentioned on the contact page of the site are accepted.',
    'terms.exclusions.weather.title': 'Weather conditions',
    'terms.exclusions.weather.snow': 'The service(s) will be automatically cancelled or postponed if the private location assigned for the work is not cleared of snow or ice or if it represents a safety risk.',
    'terms.exclusions.weather.temperature': 'The service(s) will be automatically cancelled if the weather including wind and cooling factors, except for tire and battery changes, exceed -18 degrees.',
    'terms.exclusions.insurance.title': 'Insurance',
    'terms.exclusions.insurance.content': 'At the moment, we do not perform any post-claim work for insurance. Payments via Canadian or foreign insurers are not accepted.',

    'terms.tips.title': 'Tips and Customer Relations',
    'terms.tips.policy': 'Tips are not mandatory, but they are accepted at your discretion.',
    'terms.tips.access.title': 'Access to premises',
    'terms.tips.access.content': 'To limit conflicts, no technician is authorized to enter your home or a space that is not assigned to vehicle repair. Example: going to get a part or tires from your basement.',
    'terms.tips.preparation.title': 'Customer preparation',
    'terms.tips.preparation.content': 'On the day of your appointment, make sure that if applicable, all parts are nearby to optimize the technician\'s time.',
    'terms.tips.electrical': 'Although our technicians are equipped with cordless tools, they may occasionally ask you to plug in an extension cord.',

    'terms.road.tests.title': 'Road Tests',
    'terms.road.tests.procedure': 'The technician will perform one or more road tests before or after work on your vehicle when applicable.',
    'terms.road.tests.license': 'All our technicians have a valid driver\'s license at the time of service.',
    'terms.road.tests.insurance': 'We are covered in case of accident for vehicles that do not belong to us.',

    'terms.environmental.title': 'Environmental Fees and Disposal of Used Parts',
    'terms.environmental.fees.included': 'All environmental fees for the recovery of defective parts, used oils and filters are included in the price.',
    'terms.environmental.disposal.title': 'Parts disposal',
    'terms.environmental.disposal.parts': 'With the exception of batteries provided by our services, all used parts, packaging and plastic materials will be disposed of in an environmentally friendly manner.',
    'terms.environmental.disposal.keep': 'It is your right to keep your used parts, at no additional cost, you just need to mention it to your technician.',
    'terms.environmental.disposal.no.used': 'JJ Mechanics will under no circumstances install any used parts on your vehicle.',
    'terms.environmental.protection': 'Our technicians have adequate equipment to avoid soiling your property. All used oils will be disposed of in an eco-responsible manner at no additional cost.',
    
    // Client Portal EN ANGLAIS
    'client.portal.title': 'Client Portal',
    'client.portal.subtitle': 'Manage your invoices and service history',
    'client.portal.welcome': 'Welcome to your client portal',
    'client.portal.description': 'View your invoices, download your receipts and track your service history.',
    'client.portal.search.placeholder': 'Search by invoice number, email or phone...',
    'client.portal.search.button': 'Search',
    'client.portal.invoice.number': 'Invoice #',
    'client.portal.date': 'Date',
    'client.portal.service': 'Service',
    'client.portal.amount': 'Amount',
    'client.portal.status': 'Status',
    'client.portal.actions': 'Actions',
    'client.portal.download': 'Download',
    'client.portal.view': 'View',
    'client.portal.paid': 'Paid',
    'client.portal.pending': 'Pending',
    'client.portal.no.invoices': 'No invoices found',
    'client.portal.search.tip': 'Use your email or phone number to find your invoices',
    'client.portal.loading': 'Loading...',
    'client.portal.error': 'Search error',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.reserve': 'Book',
    'common.book': 'Book'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
